# Generated by Django 4.2 on 2023-05-13 11:38

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(max_length=200)),
                ("category", models.CharField(max_length=100)),
                ("content", mdeditor.fields.MDTextField()),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("url", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "topimage",
                    models.ImageField(upload_to="images", verbose_name="トップ画像"),
                ),
                (
                    "subimage",
                    models.ImageField(upload_to="images", verbose_name="サブ画像"),
                ),
            ],
        ),
    ]
