# Generated by Django 4.2 on 2023-05-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entrance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="top",
            name="urls",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="url"
            ),
        ),
    ]
