version: '3'
services:
  db:
    image: postgres:13.1
    container_name: postgres
    volumes:
      - ./db/dbdata:/var/lib/postgresql/data
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myappdb

  django:
    restart: always
    build: .
    image: django
    container_name: django_portfolio
    expose:
      - '8080'
    tty: true
    volumes:
      - ./:/root/src
    depends_on:
      - db

  web:
    image: nginx:1.18.0
    container_name: nginx
    volumes:
      - ./web/conf:/etc/nginx/conf.d
      - ./web/uwsgi_params:/etc/nginx/uwsgi_params
      - ./src/static:/static/
    ports:
      - '80:80'
    depends_on:
      - django
