version: '3'
services:
  django:
    restart: always
    build: .
    command: python manage.py runsslserver 0.0.0.0:8989 --certificate portfolio_ssl.crt --key portfolio_ssl.key
    ports:
      - 8989:8989
    container_name: 'django_portfolio'
    working_dir: '/root/src/'
    tty: true
    volumes:
      - ./:/root/src
