version: '3'
services:
  django:
    restart: always
    build: .
    command: python3 manage.py runserver 0.0.0.0:8888
    ports:
      - 8888:8888
    container_name: 'django_portfolio'
    working_dir: '/root/src/'
    tty: true
    volumes:
      - ./:/root/src
