# Generated by Django 4.2 on 2023-05-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0005_software_technical"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="qiita",
            field=models.CharField(max_length=100, null=True, verbose_name="qiita"),
        ),
    ]
