# Generated by Django 4.2 on 2023-05-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("techblog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="subimage",
            field=models.ImageField(
                blank=True, null=True, upload_to="images", verbose_name="サブ画像"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="topimage",
            field=models.ImageField(
                blank=True, null=True, upload_to="images", verbose_name="トップ画像"
            ),
        ),
    ]
