# Generated by Django 4.2.2 on 2023-06-06 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techblog', '0002_alter_article_subimage_alter_article_topimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='subimage',
        ),
        migrations.RemoveField(
            model_name='article',
            name='topimage',
        ),
    ]
