# Generated by Django 4.2.3 on 2023-07-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('total_revenue', models.IntegerField()),
                ('stockholdersequity', models.IntegerField()),
                ('totalassets', models.IntegerField()),
                ('capitaladequancyratio', models.IntegerField()),
                ('roe', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=100)),
                ('stock_name', models.CharField(max_length=100)),
                ('market', models.CharField(max_length=100)),
                ('stock_category33', models.CharField(max_length=100)),
                ('stock_category17', models.CharField(max_length=100)),
                ('dividendRate', models.IntegerField()),
                ('dividendYield', models.IntegerField()),
                ('fiveYearAvgDividendYield', models.IntegerField()),
                ('payoutRatio', models.IntegerField()),
                ('marketcap', models.IntegerField()),
                ('totalRevenue', models.IntegerField()),
                ('roe', models.IntegerField()),
            ],
        ),
    ]
