# Generated by Django 4.2.3 on 2023-07-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_stock', '0008_alter_financialinfo_capitaladequancyratio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialinfo',
            name='capitaladequancyratio',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='roe',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='stockholdersequity',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='total_revenue',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='totalassets',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='dividendRate',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='dividendYield',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='fiveYearAvgDividendYield',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='marketcap',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='payoutRatio',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='roe',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='totalRevenue',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
