# Generated by Django 4.2.3 on 2023-07-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_stock', '0009_alter_financialinfo_capitaladequancyratio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=100)),
                ('stock_name', models.CharField(max_length=100)),
                ('want_to_buy_dividendYield', models.FloatField()),
                ('no_dividend_decrease_year', models.IntegerField(blank=True, null=True)),
                ('dividend_increase_year', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
